import "../globals.css";
import Header from "@/app/.component/Header";
import Footer from "@/app/.component/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true" >
        <Header/>
        {children} 
        <Footer/>
      </body> 
    </html>  
  );
}
